name: kcalc
description: "Calorie Counter App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  freezed_annotation: ^2.4.1
  go_router: ^13.1.0
  hooks_riverpod: ^2.4.9
  intl: ^0.19.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.11
  riverpod_lint: ^2.3.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/iconr.png"
  image_dark: "assets/iconr.png"
